CREATE TABLE IF NOT EXISTS author
(
    birth    DATE,
    id       bigint generated by default as identity,
    lastname varchar(255),
    name     varchar(255),
    primary key (id)
);

CREATE TABLE IF NOT EXISTS author_books
(
    author_id bigint not null,
    book_id   bigint not null
);

CREATE TABLE IF NOT EXISTS book
(
    publication_year integer,
    id               bigint generated by default as identity,
    publisher_id     bigint,
    title            varchar(255),
    primary key (id)
);

CREATE TABLE IF NOT EXISTS publisher
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

ALTER TABLE author_books
    ADD CONSTRAINT IF NOT EXISTS FKgg8l7xyje2rjham3sgxfk2dxm
        FOREIGN KEY (book_id)
            REFERENCES book;

ALTER TABLE author_books
    ADD CONSTRAINT IF NOT EXISTS FKfvabqdr9njwv4khjqkf1pbmma
        FOREIGN KEY (author_id)
            REFERENCES author;

ALTER TABLE book
    ADD CONSTRAINT IF NOT EXISTS FKgtvt7p649s4x80y6f4842pnfq
        FOREIGN KEY (publisher_id)
            REFERENCES publisher;
